### ISSUE TITLE
Iron tries to link to OpenSSL even with default-features=false

### ISSUE THREAD

**Issue by TyOverby** [iron/iron#399]
# Error

```
Ty@windows-desktop ~/workspace/rust/stormtrooper
$ cargo build
   Compiling openssl-sys v0.6.7
failed to run custom build command for `openssl-sys v0.6.7`
Process didn't exit successfully: `c:\Users\Ty\workspace\rust\stormtrooper\target\debug\build\openssl-sys-f0bee5fb97afc90d\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=C:\MinGW\msys\1.0\local\bin
cargo:rustc-link-search=native=C:\MinGW\msys\1.0\mingw\bin
cargo:rustc-link-search=native=C:\MinGW\msys\1.0\bin
cargo:rustc-link-search=native=c:\MinGW\bin
cargo:rustc-link-lib=dylib=ssleay32
cargo:rustc-link-lib=dylib=eay32
TARGET = Some("x86_64-pc-windows-gnu")
OPT_LEVEL = Some("0")
PROFILE = Some("debug")
TARGET = Some("x86_64-pc-windows-gnu")
debug=true opt-level=0
HOST = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CC_x86_64-pc-windows-gnu = None
CC_x86_64_pc_windows_gnu = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-gnu")
HOST = Some("x86_64-pc-windows-gnu")
CFLAGS_x86_64-pc-windows-gnu = None
CFLAGS_x86_64_pc_windows_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-o" "c:\\Users\\Ty\\workspace\\rust\\stormtrooper\\target\\debug\\build\\openssl-sys-f0bee5fb97afc90d\\out\\src\\openssl_shim.o" "-c" "src/openssl_shim.c"
ExitStatus(ExitStatus(1))


command did not execute successfully, got: exit code: 1



--- stderr
src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
 #include <openssl/hmac.h>
                          ^
compilation terminated.
thread '<main>' panicked at 'explicit panic', c:/Users/Ty\.cargo\registry\src\github.com-0a35038f75765ae4\gcc-0.3.19\src\lib.rs:771
```

# Cargo.toml

```toml
[package]
name = "stormtrooper"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]

[dependencies.ares]
path = "../ares/"

[dependencies.notify]
path = "../rsnotify/"

[dependencies.iron]
version = "0.2.*"
default-features = false

[dependencies.router]
version = "0.0.15"

[dependencies.typemap]
version = "0.3.3"
```
